# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 920abd6728978a8ed5119feb12a0f8efebfe2bb1cd064a786f84da6f8acc6a682103a15ff297d8a1143f65ad5a02906c7c4f17a19ac8b474068c8d825067469b

test:
  secret_key_base: d43855f274a475ea205dfb7c1625cc7e7eb9e004fcaa5b718bcffd7a71945a0061f6ccded07171f8e48487a976fd443f23b0e9a07905f8011495a1ea3901e123

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
